/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.Enumeration;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Lucas
 */
public class DatosGenerados extends javax.swing.JPanel {

    /**
     * Creates new form DatosGenerados
     */
    public DatosGenerados() {
        initComponents();

        JRadioButton jrb = getSelection(VentanaPrincipal.obtenerGrupoBotones()); //DEVOLVER UN JRADIO SI ES NULL!!!

        if (jrb != null) {
            String s = jrb.getText();

            jLabel4.setText(s);
        } else {
            jLabel4.setText("");
        }

        if (VentanaPrincipal.obtenerCheckBoxProgramacion().isSelected()) {
            campoEspecialidad1.setText("Programacion");
        }
        if (VentanaPrincipal.obtenerCheckBoxDiseño().isSelected()) {
            campoEspecialidad2.setText("Diseño");
        }
        if (VentanaPrincipal.obtenerCheckBoxAdministracion().isSelected()) {
            campoEspecialidad3.setText("Adminsitracion");
        }

        campoHoras.setText("" + VentanaPrincipal.obtenerSlider().getValue());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoEspecialidad1 = new javax.swing.JLabel();
        campoEspecialidad2 = new javax.swing.JLabel();
        campoEspecialidad3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoHoras = new javax.swing.JLabel();
        campoSistema = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Resultado encuesta:");

        jLabel2.setText("Sistema:");

        jLabel3.setText("Especialidad:");

        jLabel7.setText("Horas:");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 301, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSistema))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEspecialidad2)
                            .addComponent(campoEspecialidad1)
                            .addComponent(campoEspecialidad3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(campoHoras)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoSistema)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoEspecialidad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEspecialidad2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEspecialidad3)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoHoras))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoEspecialidad1;
    private javax.swing.JLabel campoEspecialidad2;
    private javax.swing.JLabel campoEspecialidad3;
    private javax.swing.JLabel campoHoras;
    private javax.swing.JLabel campoSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    public static JRadioButton getSelection(ButtonGroup group) {
        for (Enumeration e = group.getElements(); e.hasMoreElements();) {
            JRadioButton b = (JRadioButton) e.nextElement();
            if (b.getModel() == group.getSelection()) {
                return b;
            }

        }

        return null;
    }
}
